auth_demo/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from hello import views as hello_views
from accounts import views as accounts_views
from paypal.standard.ipn import urls as paypal_urls
from products import views as product_views
from magazines import views as magazine_views
from paypal_store import views as paypal_views
from threads import views as forum_views

#if settings.DEBUG:
    #import debug_toolbar

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', hello_views.get_index, name='index'),
    url(r'^register/$', accounts_views.register, name='register'),
    url(r'^profile/$', accounts_views.profile, name='profile'),
    url(r'^login/$', accounts_views.login, name='login'),
    url(r'^logout/$', accounts_views.logout, name='logout'),
    url(r'^cancel_subscription/$', accounts_views.cancel_subscription, name='cancel_subscription'),
    url(r'^subscriptions_webhook/$', accounts_views.subscriptions_webhook, name='subscriptions_webhook'),
    url(r'^a-very-hard-to-guess-url/', include(paypal_urls)),
    url(r'^products/$', product_views.all_products),
    url(r'^magazines/$', magazine_views.all_magazines),
    url(r'^paypal-return', paypal_views.paypal_return),
    url(r'^paypal-cancel', paypal_views.paypal_cancel),

    #url(r'^__debug__/', include(debug_toolbar.urls)),

    url(r'^forum/$', forum_views.forum),
    url(r'^threads/(?P<subject_id>\d+)/$', forum_views.threads, name='threads'),
    url(r'^new_thread/(?P<subject_id>\d+)/$', forum_views.new_thread, name='new_thread'),
    url(r'^thread/(?P<thread_id>\d+)/$', forum_views.thread, name='thread'),
    url(r'^post/new/(?P<thread_id>\d+)/$', forum_views.new_post, name='new_post'),
    url(r'^post/edit/(?P<thread_id>\d+)/(?P<post_id>\d+)/$',forum_views.edit_post, name='edit_post'),
    url(r'^post/delete/(?P<post_id>\d+)/$', forum_views.delete_post, name='delete_post'),
    url(r'^thread/vote/(?P<thread_id>\d+)/(?P<subject_id>\d+)/$', forum_views.thread_vote, name='cast_vote'),
]

threads/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from django.conf import settings


class Subject(models.Model):
    name = models.CharField(max_length=255)
    description = HTMLField()

    def __unicode__(self):
        return self.name

class Thread(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='threads')
    subject = models.ForeignKey(Subject, related_name='threads')
    created_at = models.DateTimeField(default=timezone.now())

class Post(models.Model):
    thread = models.ForeignKey(Thread, related_name='posts')
    comment = HTMLField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts')
    created_at = models.DateTimeField(default=timezone.now)

threads/forms.py
from django import forms
from .models import Thread, Post


class ThreadForm(forms.ModelForm):
    name = forms.CharField(label="Thread name")
    is_a_poll = forms.BooleanField(label="Include a poll?", required=False)

    class Meta:
        model = Thread
        fields = ['name']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['comment']

threads/views.py
from django.shortcuts import render, get_object_or_404
from threads.models import Subject, Thread, Post
from django.shortcuts import redirect
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.template.context_processors import csrf
from .forms import ThreadForm, PostForm
from django.forms import formset_factory
from polls.forms import PollSubjectForm, PollForm
from polls.models import PollSubject

def forum(request):
    return render(request, 'forum/forum.html', {'subjects': Subject.objects.all()})

def threads(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    return render(request, 'forum/threads.html', {'subject': subject})


@login_required
def new_thread(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    poll_subject_formset = formset_factory(PollSubjectForm, extra=3)
    if request.method == "POST":
        thread_form = ThreadForm(request.POST)
        post_form = PostForm(request.POST)
        poll_form = PollForm(request.POST)
        poll_subject_formset = poll_subject_formset(request.POST)
        if thread_form.is_valid() and post_form.is_valid() and poll_form.is_valid() and poll_subject_formset.is_valid():
            thread = thread_form.save(False)
            thread.subject = subject
            thread.user = request.user
            thread.save()

            post = post_form.save(False)
            post.user = request.user
            post.thread = thread
            post.save()

        # if request.POST.get('is_a_poll', None):

            poll = poll_form.save(False)
            poll.thread = thread
            poll.save()

        # else:

            for subject_form in poll_subject_formset:
                subject = subject_form.save(False)
                subject.poll = poll
                subject.save()

            messages.success(request, "You have created a new thread!")

            return redirect(reverse('thread', args={thread.pk}))

    else:
        thread_form = ThreadForm()
        post_form = PostForm(request.POST)
        poll_form = PollForm()
        poll_subject_formset = poll_subject_formset()

    args = {
        'thread_form': thread_form,
        'post_form': post_form,
        'subject': subject,
        'poll_form': poll_form,
        'poll_subject_formset': poll_subject_formset,
    }

    args.update(csrf(request))

    return render(request, 'forum/thread_form.html', args)
def thread(request, thread_id):
    thread_ = get_object_or_404(Thread, pk=thread_id)
    args = {'thread': thread_}
    args.update(csrf(request))
    return render(request, 'forum/thread.html', args)


def new_post(request, thread_id):
    thread = get_object_or_404(Thread, pk=thread_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(False)
            post.thread = thread
            post.user = request.user
            post.save()

            messages.success(request, "Your post has been added to the thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm()

    args = {
        'form': form,
        'form_action': reverse('new_post', args={thread.id}),
        'button_text': 'Update Post'
    }
    args.update(csrf(request))

    return render(request, 'forum/post_form.html', args)


@login_required
def edit_post(request, thread_id, post_id):
    thread = get_object_or_404(Thread, pk=thread_id)
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "You have updated your thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm(instance=post)

    args = {
        'form': form,
        'form_action': reverse('edit_post', kwargs={"thread_id": thread.id, "post_id": post.id}),
        'button_text': 'Update Post'
    }
    args.update(csrf(request))

    return render(request, 'forum/post_form.html', args)


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    thread_id = post.thread.id
    post.delete()

    messages.success(request, "Your post was deleted!")

    return redirect(reverse('thread', args={thread_id}))


@login_required
def thread_vote(request, thread_id, subject_id):
    thread = Thread.objects.get(id=thread_id)

    subject = thread.poll.votes.filter(user=request.user)

    if subject:
        messages.error(request, "You already voted on this!... "
                                "You're not trying to cheat are you?")
        return redirect(reverse('thread', args={thread_id}))

    subject = PollSubject.objects.get(id=subject_id)

    subject.votes.create(poll=subject.poll, user=request.user)

    messages.success(request, "We've registered your vote!")

    return redirect(reverse('thread', args={thread_id}))

threads/templates/forum/forum.html
{% extends "base.html" %}
{% load thread_extras %}
{% block content %}
   {% load bootstrap_tags %}
   {% for subject in subjects %}
       <section class="subject">
           <h2><a href="{% url "threads" subject.id %}">{{ subject.name }}</a></h2>
           <p>
               <a href="{% url "threads" subject.id %}">
                   {% autoescape off %}{{ subject.description }}{% endautoescape %}
               </a>
           </p>
           <table>
               <tr>
                   <th>THREADS&nbsp;&nbsp;</th>
                   <th> POSTS</th>
               </tr>
               <tr>
                   <td>{{ subject.threads.count }}</td>
                   <td>{{ subject|get_total_subject_posts }}</td>
               </tr>
           </table>
       </section>
   {% endfor %}
{% endblock %}

threads/templates/forum/post.html
{% load staticfiles %}
{% load emoticons_tags %}
<section class="row comment col-md-9">
 <div class="col-md-3 comment-profile">
   <p><img src="{% static 'images/user.png' %}" /></p>
   <p>{{ post.user.username }}</p>
   <p>{{ post.user.posts.count }} POSTS</p>
 </div>
 <div class="col-md-9 ">
   <div class="comment-content">
     {% autoescape off %}
       {{ post.comment|emoticons }}
     {% endautoescape %}
   </div>
   {% include "comment_details.html" %}
 </div>

</section>

threads/templates/forum/post_form.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% load staticfiles %}
{% block head_js %}
<script src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
<script type="text/javascript">
 tinyMCE.init({
   mode: "textareas",
   theme: "modern",
   plugins: "paste",
});
</script>
{% endblock %}
{% block content %}
 <section>
   <div class="col-md-9">
     <form method="post" action="{{ form_action }}">
       {% csrf_token %}
       {{ form|as_bootstrap }}
       <div class="form-group">
         <button type="submit" class="btn btn-primary">{{button_text}}</button>
       </div>
     </form>
   </div>
 </section>
{% endblock %}

threads/templates/forum/thread.html
{% extends "base.html" %}
{% load thread_extras %}
{% load staticfiles %}
{% block content %}

 <div class="row header">

   <div class="container">
     <h2>{{ thread.name }}</h2>
     <div class="col-md-12">
         <table class="table">
             <tbody>
             <tr>
                 <th>
                   CREATED
                 </th>
                 <th>OWNER</th>
                 <th>LAST POST</th>
             </tr>
             <tr>
                 <td>
                   <time datetime="{{ thread.created_at }}">
                    {{ thread.created_at|started_time }}
                   </time>
                 </td>
                 <td>{{ thread.user.username }}</td>
                 <td>{% last_posted_user_name thread %}</td>
             </tr>
           </tbody>
         </table>
     </div>
       {% if thread.poll %}
               <div class="container">
                   <div class="col-md-6">
                       <h2>Poll</h2>
                       <strong>{{ thread.poll.question }}</strong><br><br>

                       <p>Here’s how the votes are so far:</p>
                     {% for subject in thread.poll.subjects.all %}
                           <div class="col-md-10">
                               <strong>{{ subject.name }}</strong>
                               <span class="pull-right">{{ subject|vote_percentage }}%</span>
                           </div>
                           {% user_vote_button thread subject user %}
                        <div class="col-md-10">
                         <div class="progress">
                           <div class="progress-bar progress-bar-info" role="progressbar"
                            aria-value="{{ subject|vote_percentage }}" aria-valuemin="0"
                            aria-valuemax="100" style="width:{{ subject|vote_percentage }}%;">
                           </div>
                         </div>
                        </div>
                      {% endfor %}
                   </div>
               </div>
        {% endif %}

     {% if user.is_authenticated %}
       <p>
         <a href="{% url 'new_post' thread.id %}" class="btn btn-primary">New post</a>
       </p>
     {% endif %}
   </div>
 </div>
 <div class="container">
   {% for post in thread.posts.all %}
     {% include "forum/post.html" %}
   {% endfor %}
 </div>
{% endblock %}

threads/templates/forum/thread_form.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% load staticfiles %}

{% block head_js %}
   <script type="text/javascript" src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <script type="application/javascript">
       tinyMCE.init({mode: "textareas", theme: 'modern', plugins: 'paste'})

   </script>
{% endblock %}


{% block content %}
   <section>
       <div class="col-md-9">
           <form method="post" action="{% url 'new_thread' subject.id %}">
               {% csrf_token %}
               <div class="form-group">
                   {{ thread_form | as_bootstrap }}
                   <hr>
                   {{ post_form | as_bootstrap }}
               </div>
               <div id="poll_form" class="form-group">
                   {{ poll_form|as_bootstrap }}
                   {{ poll_subject_formset.management_form }}
                   {% for poll_subject_form in poll_subject_formset %}
                       {{ poll_subject_form|as_bootstrap }}
                   {% endfor %}
               </div>
               <div class="form-group">
                   <button type="submit" class="btn-primary"> Post New Thread</button>
               </div>
           </form>
       </div>
   </section>
<script>
$(function() {
    if (!$('#id_is_a_poll').is('checked')) {
        $('#poll_form').hide()
    }

    $('#id_is_a_poll').click(function(el) {
        var poll_form = $('#poll_form')

        if (poll_form.is(":visible")) {
            poll_form.hide()
        } else {
            poll_form.show()
        }
    })
})
</script>
{% endblock %}

threads/templates/forum/thread_item.html
<section class="thread">
 <header>
   <table>
     <tr>
       <td>
         <a href="{% url 'thread' thread.id %}"><h4>{{ thread.name }}</h4></a>
       </td>
     </tr>
   </table>

 </header>
</section>

threads/templates/forum/threads.html
{% extends "base.html" %}
{% load thread_extras %}
{% block content %}
 <div class="row header">
   <div class="jumbotron"><h1>{{ subject.name }}</h1></div>
 </div>
 <div class="col-md-12">
   {% if user.is_authenticated %}
     <p>
       <a href="{% url 'new_thread' subject.id %}" class="btn btn-primary">New Thread</a>
     </p>
   {% endif %}
   {% for thread in subject.threads.all %}
     {% include "forum/thread_item.html" %}
   {% endfor %}
 </div>
{% endblock %}